theme = "macchiato"
actions_as_menu = true

[providers.actions]
bitwarden = [
  { action = "copypassword", label = "copy password", default = true, bind = "Return" },
  { action = "typepassword", label = "type password", default = true, bind = "ctrl p" },
  { action = "copyusername", label = "copy username", bind = "shift Return" },
  { action = "typeusername", label = "type username", bind = "ctrl u" },
  { action = "copytotp", label = "copy 2fa", bind = "ctrl Return" },
  { action = "typetotp", label = "type 2fa", bind = "ctrl t" },
  { action = "syncvault", label = "sync", bind = "ctrl s" },
]
